### ISSUE TITLE
Some logos are missing on contao.github.io/package-metadata/meta

### ISSUE THREAD

**Issue by fritzmg** [contao/package-metadata#275]
Since a few days, a lot of different logos aren't visible any more on https://extensions.contao.org/. The logos are present in the repository and they are still referenced on extensions.contao.org, but the Logo URL leads to 404. Examples:

* https://contao.github.io/package-metadata/meta/contao-themes-net/odd-theme-bundle/logo.svg from 
https://extensions.contao.org/?p=contao-themes-net%2Fodd-theme-bundle » 
https://github.com/contao/package-metadata/blob/main/meta/contao-themes-net/odd-theme-bundle/logo.svg

* https://contao.github.io/package-metadata/meta/contao-themes-net/mate-theme-bundle/logo.svg from 
https://extensions.contao.org/?p=contao-themes-net%2Fmate-theme-bundle » 
https://github.com/contao/package-metadata/blob/main/meta/contao-themes-net/mate-theme-bundle/logo.svg

* https://contao.github.io/package-metadata/meta/netzhirsch/cookie-opt-in-bundle/logo.svg from 
https://extensions.contao.org/?p=netzhirsch%2Fcookie-opt-in-bundle » 
https://github.com/contao/package-metadata/blob/main/meta/netzhirsch/cookie-opt-in-bundle/logo.svg

**Comment by Toflar** [comment]
Fixed.
