### ISSUE TITLE
Actions: not anymore every 30 minutes

### ISSUE THREAD

**Issue by mathContao** [contao/package-metadata#340]
It looks like that the actions changed from 30 minutes to more (I guess 45 minutes or 60 minutes)

![grafik](https://user-images.githubusercontent.com/1645099/104848475-629acf80-58e5-11eb-86b5-337ffffc12e6.png)

**Comment by Toflar** [comment]
Let's see if GitHub fixes that then.

**Comment by mathContao** [comment]
looks fine now
![grafik](https://user-images.githubusercontent.com/1645099/106399029-96faa980-6416-11eb-824b-c225e9eab35f.png)
