### ISSUE TITLE
Fatal error in spell check

### ISSUE THREAD

**Issue by Total-Reality** [contao/package-metadata#410]
It is not possible to add files via a pull request. The validation checker has an error perhaps.

https://github.com/contao/package-metadata/runs/5264637495?check_suite_focus=true

Or see the pull request here: https://github.com/contao/package-metadata/pull/409

I tested everything, nothing works.

**Comment by fritzmg** [comment]
The problem is, that the current linter implementation does not work if the Pull Request deletes files. I think we should just ignore any non-existing files.
