### ISSUE TITLE
Review whitelist.txt

### ISSUE THREAD

**Issue by Toflar** [contao/package-metadata#54]
Hey everyone,

I've implemented automated spell checking on meta data (at the moment only `title` and `description` are spell checked against) so that we can further improve the quality of our meta data.

It is based on GNU Aspell (http://aspell.net).

There's a `whitelist.txt` file which contains all exceptions to what Aspell thinks is wrong and for the sake of simplicity I've added everything it found during the first run to that whitelist. So basically the whitelist now certainly contains words that are incorrectly spelled.

It would be great if you could help to review that file and if you find something, create a PR where you:

* remove that word from the `whitelist.txt`
* fix the issues in the linter finds.

**Comment by Toflar** [comment]
Example: https://github.com/contao/package-metadata/commit/ef3ccad1300cdb7ea6884e5a0bc46ccd196bf1e8

**Comment by MDevster** [comment]
We should not set the hurdle for new commits so high. I do not believe that all users want to install all dictionaries to run the tests and just want to maintain their own native language. What happens if a mistake appears in a language that is foreign to me? The user will probably just give up.

**Comment by Toflar** [comment]
You don‘t have to install anything at all. Just do the changes and create a PR. Travis will then tell you what‘s wrong and you can continue to update your PR to fix the issues.

**Comment by Toflar** [comment]
I could optimize this, that‘s not a problem.

**Comment by Toflar** [comment]
That's true, should not be a big deal to do, I'll leave the issue open.

**Comment by Toflar** [comment]
Whitelists are now localized, thanks @dmolineus
