### ISSUE TITLE
Language and spelling in package descriptions

### ISSUE THREAD

**Issue by bezin** [contao/package-metadata#78]
* Do we enforce American or British English, e.g. optimized vs. optimised? We should decide and add this to the ReadMe. Which locale is used on Travis?
* Are keywords supposed to be all lowercase? We actually give that example in the ReadMe, but I wonder if we should enforce correct grammar like Back end, Contao, CSS, Icon font, ...?

**Comment by aschempp** [comment]
> Do we enforce American or British English, e.g. optimized vs. optimised?

I think the text belongs to the author of the package, so they are free to use the language they prefer

> * Are keywords supposed to be all lowercase?

They are, to me. It does not really matter though, as they do not appear anywhere and are only used for the search which surely is case insensitive.
