### ISSUE TITLE
vendor logo not used automatically for private packages?

### ISSUE THREAD

**Issue by fritzmg** [contao/package-metadata#94]
It looks like the vendor logo is not used automatically for private packages:

![Screenshot_2019-04-11 Contao Manager 1 1 4](https://user-images.githubusercontent.com/4970961/55964492-1a14a380-5c75-11e9-885c-a13218f46186.png)

Is this by design?

**Comment by Toflar** [comment]
How's that related to the package indexer? It's not public (https://packagist.org/?query=inspiredminds%2Fcontao-im-framework) nor is there any data in the package metadata repository.

**Comment by fritzmg** [comment]
Well yes - but why is the default logo for the vendor not working for private packages? Is this by design, i.e. do I have to provide a `meta/vendor/private-package/logo.svg` for each private package, even though there is already a `meta/vendor/logo.svg` present?

**Comment by Toflar** [comment]
No idea, that issue should go to the Manager.

**Comment by fritzmg** [comment]
Ah ok, I guess I misunderstood how the Contao Manager retrieves the meta data.

**Comment by aschempp** [comment]
@fritzmg the logos is only used for search result data, not for any other packages.

**Comment by fritzmg** [comment]
Hm, yeah but in the package over view I can see the default logo for the `inspiredminds/` vendor on any package - even though no specific `logo.svg` has been provided for the specific package. Except for private packages with the same vendor name.

**Comment by fritzmg** [comment]
Yes, right :). So it's by design, that for private packages, you must specify the logo in the meta data for each package and the vendor fallback logo will not work.
